---
sensor:
  number:
    _key: hard_disk_number
    _type: int

  device:
    _key: hard_disk_device
    _type: str

  interface:
    _key: interface
    _type: str

  model_id:
    _key: hard_disk_model_id
    _type: str

  revision:
    _key: firmware_revision
    _type: str
  
  serial_no:
    _key: hard_disk_serial_number
    _type: str

  total_size:
    _key: total_size
    _type: float
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: 'mb'
    value_template: |-
      {% set total_size = value_json.total_size %}
      {{ total_size.split()[0] | int(0) }}     

  current_temperature:
    _key: current_temperature
    _type: float
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    value_template: |-
      {% set temperature = value_json.current_temperature %}
      {{ temperature.split()[0] | int(0) }}     

  max_temp:
    _key: maximum_temperature_during_entire_lifespan
    _type: float
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    value_template: |-
      {% set temperature = value_json.maximum_temperature_during_entire_lifespan %}
      {{ temperature.split()[0] | int(0) }}    

  power_on_time:
    _key: power_on_time
    _type: int
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: 'days'
    icon: mdi:clock
    value_template: |-
      {% set days = value_json.power_on_time %}
      {{ days.split()[0] | int(0) }}  

  estimated_lifetime:
    _key: estimated_remaining_lifetime
    _type: int
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: 'days'
    icon: mdi:clock-alert
    value_template: |-
      {% set days = value_json.estimated_remaining_lifetime.split('days')[0].split() %}
      {{ days| last | int(0) }}    

  lifetime_writes:
    _key: lifetime_writes
    _type: float
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: 'tb'
    value_template: |-
      {% if 'lifetime_writes' in value_json %}
        {% set gb = value_json.lifetime_writes %}
        {% if 'GB' in gb %}
          {{ gb.split()[0] | float(0) | multiply(0.001) | round(2) }}
        {% else %}
          {{ gb.split()[0] | float(0) | round(2) }}
        {% endif %}
      {% endif %}     

  health:
    _key: health
    _type: float
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: '%'
    value_template: |-
      {% set health = value_json.health %}
      {{ health.split()[0] | int(0) }}
    

  performance:
    _key: performance
    _type: float
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: '%'
    value_template: |-
      {% set performance = value_json.performance %}
      {{ performance.split()[0] | int(0) }}    

  description:
    _key: description
    _type: str
    value_template: |-
      {{ value_json.description | truncate(255) }}

  tip:
    _key: tip
    _type: str